using MobiusEditor.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace MobiusEditor.Utility
{
    public static class MixScanCache
    {
        const string MIXCACHEINFO =
            //  "_______09________19________29________39________49________59________69________79________89________99"
            "; MOBIUS MAP EDITOR MIX SCAN CACHE\r\n; DO NOT EDIT THIS FILE.\r\n;\r\n" +
            "; This file contains the cached result of scanning all found .mix archives to find missions that\r\n" +
            "; can be opened by Mobius Map editor. Manually editing this file may cause unintended behavior or\r\n" +
            "; crashes in the editor. If this file got corrupted somehow, simply delete it and let the editor\r\n" +
            "; regenerate it.\r\n\r\n";

        public static Dictionary<GameType, List<string>>[] FindMissionMixFiles(MixFileNameGenerator romfis, string cachedMixInfoFile, Func<bool> checkAbort)
        {
            const string PREFIX_CLASSIC = "Classic_";
            const string PREFIX_REMASTER = "Remaster_";
            INI cachedMixIni = new INI();
            INI newMixIni = new INI();
            if (File.Exists(cachedMixInfoFile))
            {
                try
                {
                    using (TextReader reader = new StreamReader(cachedMixInfoFile, new UTF8Encoding(false)))
                    {
                        cachedMixIni.Parse(reader);
                    }
                }
                catch { /* ignore */ }
            }
            HashSet<string> classicBaseFolders = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            HashSet<string> remasterBaseFolders = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            Dictionary<GameType, List<string>> classicMixFiles = new Dictionary<GameType, List<string>>();
            Dictionary<GameType, List<string>> remasterMixFiles = new Dictionary<GameType, List<string>>();
            string remasterPath = StartupLoader.GetRemasterRunPath(Program.RemasterSteamId, false);
            if (remasterPath != null)
            {
                remasterPath = Path.Combine(remasterPath, Globals.MegafilePath);
            }
            GameInfo[] gamesAll = GameTypeFactory.GetGameInfos(true);
            GameInfo[] games = GameTypeFactory.GetGameInfos();
            for (int i = 0; i < games.Length; ++i)
            {
                GameInfo gameInfo = games[i];
                if (checkAbort())
                {
                    return null;
                }
                if (gameInfo == null)
                {
                    GameInfo gameInfoReal = gamesAll[i];
                    // Game is currently not being handled. Preserve its entries, though,
                    // or two installed editors configured for different games will keep resetting each other.
                    INISection oldSecClassic = cachedMixIni[PREFIX_CLASSIC + gameInfoReal.IniName];
                    if (oldSecClassic != null)
                        newMixIni.Sections.Add(oldSecClassic);
                    INISection oldSecRemaster = cachedMixIni[PREFIX_REMASTER + gameInfoReal.IniName];
                    if (oldSecRemaster != null)
                        newMixIni.Sections.Add(oldSecRemaster);
                    continue;
                }
                string classicRoot = Path.GetFullPath(Path.Combine(Program.ApplicationPath, gameInfo.ClassicFolder));
                if (!classicBaseFolders.Contains(classicRoot) && Directory.Exists(classicRoot))
                {
                    classicBaseFolders.Add(classicRoot);
                    string[] allMixFiles = Directory.GetFiles(classicRoot, "*.mix", SearchOption.TopDirectoryOnly);
                    List<string> validMixFiles = GetMixFilesWithMissions(gameInfo, allMixFiles, romfis, cachedMixIni, newMixIni, PREFIX_CLASSIC, checkAbort);
                    if (validMixFiles.Count > 0)
                    {
                        classicMixFiles.Add(gameInfo.GameType, validMixFiles);
                    }
                }
                if (remasterPath == null)
                {
                    continue;
                }
                string remasterRoot = Path.GetFullPath(Path.Combine(remasterPath, gameInfo.ClassicFolderRemaster));
                if (!remasterBaseFolders.Contains(remasterRoot) && Directory.Exists(remasterRoot))
                {
                    remasterBaseFolders.Add(remasterRoot);
                    string[] allMixFiles = Directory.GetFiles(remasterRoot, "*.mix", SearchOption.AllDirectories);
                    List<string> validMixFiles = GetMixFilesWithMissions(gameInfo, allMixFiles, romfis, cachedMixIni, newMixIni, PREFIX_REMASTER, checkAbort);
                    if (validMixFiles.Count > 0)
                    {
                        remasterMixFiles.Add(gameInfo.GameType, validMixFiles);
                    }
                }
            }
            if (checkAbort())
            {
                return null;
            }
            string cachedIni = MIXCACHEINFO + newMixIni.ToString("\r\n");
            string cachedMixInfoPath = Path.GetDirectoryName(cachedMixInfoFile);
            if (!Directory.Exists(cachedMixInfoPath))
            {
                Directory.CreateDirectory(cachedMixInfoPath);
            }
            File.WriteAllText(cachedMixInfoFile, cachedIni);
            return new[] { classicMixFiles, remasterMixFiles };
        }

        private static List<string> GetMixFilesWithMissions(GameInfo gameInfo, string[] allMixFiles, MixFileNameGenerator romfis, INI cachedMixIni,
            INI newMixIni, string iniPrefix, Func<bool> checkAbort)
        {
            string iniSectionName = iniPrefix + gameInfo.IniName;
            INISection curGameIniSection = cachedMixIni[iniSectionName];
            INISection newGameIniSection = new INISection(iniSectionName);
            List<string> validMixFiles = new List<string>();
            foreach (string mixFile in allMixFiles)
            {
                if (checkAbort())
                {
                    return validMixFiles;
                }
                string fullMixPath = Path.GetFullPath(mixFile);
                bool mixHandledFromIni = CheckMixPathInIni(fullMixPath, validMixFiles, curGameIniSection, newGameIniSection);
                if (mixHandledFromIni || !MixFile.CheckValidMix(fullMixPath, gameInfo.CanUseNewMixFormat))
                {
                    continue;
                }
                using (MixFile mix = new MixFile(fullMixPath, gameInfo.CanUseNewMixFormat))
                {
                    romfis.IdentifyMixFile(mix, gameInfo.IniName);
                    List<MixEntry> entries = MixContentAnalysis.AnalyseFiles(mix, true, null);
                    int hasMissions = 0;
                    if (entries.Any(e => e.Type == MixContentType.MapTd || e.Type == MixContentType.MapRa || e.Type == MixContentType.MapSole))
                    {
                        validMixFiles.Add(fullMixPath);
                        hasMissions = 1;
                    }
                    // Format: c:\path\mixfile.mix,submix=lastMod,filesize,hasMissions
                    long timeStamp = File.GetLastWriteTime(fullMixPath).Ticks;
                    FileInfo mixInfo = new FileInfo(fullMixPath);
                    string fullMixPathIni = Uri.EscapeDataString("\"" + mixInfo.FullName + "\"");
                    newGameIniSection[fullMixPathIni] = timeStamp.ToString() + "," + mixInfo.Length.ToString() + "," + hasMissions.ToString();
                    // Scan deeper mix files.
                    foreach (MixEntry entry in entries.Where(entr => entr.Type == MixContentType.Mix))
                    {
                        string subName = MixPath.GetMixEntryName(entry);
                        string subMixPath = fullMixPath + ";" + subName;
                        string subMixPathIni = Uri.EscapeDataString("\"" + subMixPath + "\"");
                        hasMissions = 0;
                        using (MixFile subMix = new MixFile(mix, entry))
                        {
                            romfis.IdentifyMixFile(subMix, gameInfo.IniName);
                            List<MixEntry> subEntries = MixContentAnalysis.AnalyseFiles(subMix, true, null);
                            if (subEntries.Any(e => e.Type == MixContentType.MapTd || e.Type == MixContentType.MapRa || e.Type == MixContentType.MapSole))
                            {
                                validMixFiles.Add(subMixPath);
                                hasMissions = 1;
                            }
                            newGameIniSection[subMixPathIni] = timeStamp.ToString() + "," + mixInfo.Length.ToString() + "," + hasMissions.ToString();
                        }
                    }
                }
            }
            // Replace old info with new info.
            newMixIni.Sections.Add(newGameIniSection);
            return validMixFiles;
        }

        private static bool CheckMixPathInIni(string fullMixPath, List<string> validMixFiles, INISection curGameIniSection, INISection newGameIniSection)
        {
            if (curGameIniSection == null)
            {
                return false;
            }
            Dictionary<string, string> allKeys = curGameIniSection.Keys.ToDictionary();
            List<string> mixPaths = allKeys.Keys.ToList();
            for (int i = 0; i < mixPaths.Count; ++i)
            {
                string path = mixPaths[i];
                if (path.Length > 0 && path[0] == '%')
                {
                    mixPaths[i] = Uri.UnescapeDataString(path).Trim('\"');
                }
            }
            string fullMixPathIni = Uri.EscapeDataString("\"" + fullMixPath + "\"");
            string mainMixInfo = curGameIniSection.Keys.TryGetValue(fullMixPathIni) ?? curGameIniSection.Keys.TryGetValue(fullMixPath);
            if (mainMixInfo == null)
            {
                return false;
            }
            // Format: c:\path\mixfile.mix,submix=lastMod,filesize,hasMissions
            string[] mainMixData = mainMixInfo.Split(',');
            if (mainMixData.Length < 3)
            {
                return false;
            }
            long timeStamp;
            long size;
            int hasMissions;
            if (!Int64.TryParse(mainMixData[0], out timeStamp) || !Int64.TryParse(mainMixData[1], out size) || !Int32.TryParse(mainMixData[2], out hasMissions))
            {
                return false;
            }
            FileInfo mixInfo = new FileInfo(fullMixPath);
            if (!mixInfo.Exists)
            {
                return false;
            }
            long fileSize = mixInfo.Length;
            long fileModTime = File.GetLastWriteTime(fullMixPath).Ticks;
            if (mixInfo.Length != size || timeStamp != fileModTime)
            {
                return false;
            }
            if (hasMissions == 1)
            {
                validMixFiles.Add(fullMixPath);
            }
            newGameIniSection[fullMixPathIni] = mainMixInfo;
            string subMixPathOld = fullMixPath + ",";
            string subMixPathReplace = fullMixPath + ";";
            foreach (string mixPath in mixPaths)
            {
                if (mixPath.StartsWith(subMixPathReplace) || mixPath.StartsWith(subMixPathOld))
                {
                    string mixPathIni = Uri.EscapeDataString("\"" + mixPath + "\"");
                    string subMixInfo = curGameIniSection.Keys.TryGetValue(mixPathIni) ?? curGameIniSection.Keys.TryGetValue(mixPath);
                    string usableMixPath = subMixPathReplace + mixPath.Substring(subMixPathOld.Length);
                    string[] subMixData = subMixInfo.Split(',');
                    if (subMixData.Length < 3)
                    {
                        continue;
                    }
                    // Sub-mix info contains the hash and size of the parent, and whether the sub-mix contains missions.
                    if (!Int64.TryParse(subMixData[0], out timeStamp) || !Int64.TryParse(subMixData[1], out size) || !Int32.TryParse(subMixData[2], out hasMissions)
                        || timeStamp != fileModTime || size != fileSize)
                    {
                        continue;
                    }
                    newGameIniSection[mixPathIni] = subMixInfo;
                    if (hasMissions == 1)
                    {
                        validMixFiles.Add(usableMixPath);
                    }
                }
            }
            return true;
        }
    }
}
